# Sprint_10

L’objectiu d’aquest sprint és aplicar de manera pràctica vàries tasques de neteja, resum i analítica de dades utilitzant la llibreria Pandas. Addicionalment també treballaràs en automatizar processos i resoldre problemes complexes.

Descripció
En aquesta tasca t’enfrontaràs a un exercici de neteja i analítica de dades.

Tenim un dataset provinent d’una enquesta als nostres treballadors i treballadors, i hem de garantir que les dades es processes correctament, tant en format com en llegibilitat.

## Nivell 1
#### 1.
Importa com un DataFrame l'arxiu sprint10.xlsx. Assegura't que el fitxer s'importa correctament, amb els noms de columnes que li corresponen, sense manipular l'arxiu original.

Ordena el DataFrame pel país d'origen. En cas d'empat, ordena pel nom de la ciutat.

Mostra les primeres 10 files.

Addicionalment, fes un print on comprovi que el DNI només té valors únics.

In [142]:
import pandas as pd
import openpyxl
import numpy as np
from datetime import date

In [108]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.3 -> 26.1
[notice] To update, run: pip install --upgrade pip

In [109]:
# importacio (amb ajuda d openpyxl)
df = pd.read_excel("/Users/didi/Desktop/Data_Analisis/Especialitat/Sprint_10/sprint10.xlsx")
df

,Dades de l'enquesta de treballadors 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Generades aleatòriament per seguretat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
3,0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1.144 €,NaN,True,Grup B
4,1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1.253 €,True,NaN,Grup A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,995,Marta,Ferrer Ferrer,25161375F,Espanya,Sevilla,1,6,1951,D,1.216 €,NaN,True,Grup B
999,996,Joan,García,52145541P,Espanya,Sevilla,11,4,1959,H,971 €,NaN,True,Grup A
1000,997,Laia,Ferrer Martínez,69760120X,Espanya,Barcelona,11,11,1980,D,682 €,NaN,True,Grup A
1001,998,Jordi,García,82947791W,Espanya,Barcelona,23,5,1984,H,1.699 €,True,NaN,Grup C
1002,999,Clara,Sánchez López,89253307W,Espanya,Bilbao,1,8,1952,D,1.217 €,NaN,True,Grup A

In [110]:
# neteja de files i columnes
df=df.drop(columns=["Dades de l'enquesta de treballadors 2025"])

In [111]:
# eliminar files
df=df.drop([0,1])

In [112]:
# assignar capçaleres
noves_capçaleres = df.iloc[0]
df_cap= df[1:]
df_cap.columns=noves_capçaleres
df_cap.columns.name=None
df_cap= df_cap.reset_index(drop=True)

In [113]:
df_cap

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1.144 €,NaN,True,Grup B
1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1.253 €,True,NaN,Grup A
2,Fatima,Fassi,38141675A,Marroc,Rabat,6,11,2005,A,1.441 €,True,NaN,Grup A
3,Khadija,Bennani Bennani,59157262R,Marroc,Rabat,20,1,1995,D,1.944 €,NaN,True,Grup B
4,Toni,Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1.043 €,NaN,True,Grup A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Marta,Ferrer Ferrer,25161375F,Espanya,Sevilla,1,6,1951,D,1.216 €,NaN,True,Grup B
996,Joan,García,52145541P,Espanya,Sevilla,11,4,1959,H,971 €,NaN,True,Grup A
997,Laia,Ferrer Martínez,69760120X,Espanya,Barcelona,11,11,1980,D,682 €,NaN,True,Grup A
998,Jordi,García,82947791W,Espanya,Barcelona,23,5,1984,H,1.699 €,True,NaN,Grup C
999,Clara,Sánchez López,89253307W,Espanya,Bilbao,1,8,1952,D,1.217 €,NaN,True,Grup A

In [114]:
# Ordenar per pais d origen i ciutat
df_cap.sort_values(by=["País d'origen", 'Ciutat'], ascending=True).reset_index(drop=True)

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
0,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,True,Grup A
1,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,True,NaN,Grup B
2,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,True,Grup B
3,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,True,NaN,Grup B
4,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,True,NaN,Grup D
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Emily,Taylor Jones,89577876S,Regne Unit,Manchester,28,3,1958,D,2.033 €,NaN,True,Grup B
996,George,Brown Jones,57441590Y,Regne Unit,Manchester,27,12,1979,H,1.130 €,True,NaN,Grup A
997,Olivia,Brown Brown,58204038A,Regne Unit,Manchester,28,8,1952,A,1.023 €,NaN,True,Grup A
998,Isla,Jones Brown,28367234K,Regne Unit,Manchester,28,3,1999,D,1.197 €,NaN,True,Grup A
999,William,Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1.405 €,True,NaN,Grup A

In [115]:
# mostrar 10 files primeres
df_cap.head(10)

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1.144 €,NaN,True,Grup B
1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1.253 €,True,NaN,Grup A
2,Fatima,Fassi,38141675A,Marroc,Rabat,6,11,2005,A,1.441 €,True,NaN,Grup A
3,Khadija,Bennani Bennani,59157262R,Marroc,Rabat,20,1,1995,D,1.944 €,NaN,True,Grup B
4,Toni,Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1.043 €,NaN,True,Grup A
5,Laia,Castells Ferrer,26930927E,Espanya,Madrid,16,12,1953,A,2.611 €,NaN,True,Grup D
6,Carla,García,78247593G,Espanya,València,24,12,1957,D,942 €,NaN,True,Grup A
7,Marco,Rossi,21774231J,Itàlia,Torí,3,11,2002,A,1.494 €,NaN,True,Grup A
8,Alessia,Rossi,87316866D,Itàlia,Milà,6,12,1989,D,1.366 €,NaN,True,Grup A
9,Toni,Martínez,14219925Z,Espanya,Barcelona,16,5,1964,H,891 €,NaN,True,Grup A

In [116]:
# print comprovant que dni son valors unics
print(df_cap['DNI'].is_unique)

True

#### 2.

In [117]:
# Crea una columna que sigui el nom complet.
df_cap['Nom complet'] = df_cap['Nom'] + " " + df_cap['Cognoms']

# Crea una columna si la persona és nascuda a Espanya o no.
df_cap['Naixament_Espanya'] = np.where(df_cap["País d'origen"] == 'Espanya', 'Sí', 'No')

# Posa el DNI com a índex del DataFrame (noms de files).
df_cap=df_cap.set_index('DNI')

In [118]:
# Substitueix el nom de les columnes Dia de Naixement, Mes de Naixement i Any de Naixement per Dia, Mes i Any.
df_cap = df_cap.rename(columns={'Dia de Naixement': 'Dia', 'Mes de Naixement': 'Mes', 'Any de Naixement':'Any'})
# Substitueix H per Home, D per Dona, A per Altres i NC per una dada faltant (nan/null/na).
df_cap['Gènere'] = df_cap['Gènere'].replace('H', 'Home')
df_cap['Gènere'] = df_cap['Gènere'].replace('D', 'Dona')
df_cap['Gènere'] = df_cap['Gènere'].replace('A', 'Altres')
df_cap['Gènere'] = df_cap['Gènere'].replace('NC', np.nan )

# Mostra tots els canvis que has realitzat en una sola taula.
df_cap

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nom complet,Naixament_Espanya
DNI,,,,,,,,,,,,,,
16928694K,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Dona,1.144 €,NaN,True,Grup B,Inês Ferreira Silva,No
27724652S,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Dona,1.253 €,True,NaN,Grup A,Clara Sánchez Martínez,Sí
38141675A,Fatima,Fassi,Marroc,Rabat,6,11,2005,Altres,1.441 €,True,NaN,Grup A,Fatima Fassi,No
59157262R,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Dona,1.944 €,NaN,True,Grup B,Khadija Bennani Bennani,No
69630528M,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Home,1.043 €,NaN,True,Grup A,Toni Sánchez García,Sí
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Dona,1.216 €,NaN,True,Grup B,Marta Ferrer Ferrer,Sí
52145541P,Joan,García,Espanya,Sevilla,11,4,1959,Home,971 €,NaN,True,Grup A,Joan García,Sí
69760120X,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Dona,682 €,NaN,True,Grup A,Laia Ferrer Martínez,Sí
82947791W,Jordi,García,Espanya,Barcelona,23,5,1984,Home,1.699 €,True,NaN,Grup C,Jordi García,Sí
89253307W,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Dona,1.217 €,NaN,True,Grup A,Clara Sánchez López,Sí

#### 3.
Junta les columnes Fills i No Fills en una sola columna, utilitzant el mètode .apply() i definint una funció que resolgui el problema. La columna nova ha de dir-se "Fills" i prendre els valors "Sí" o "No".

In [119]:
def fills_si_no(x):
        if x == True:
            return'Sí'
        else:
            return 'No'
        

df_cap['Fills']=df_cap['Fills'].apply(fills_si_no)
df_cap.drop('No Fills', axis='columns', inplace=True)

df_cap

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,Grup Professional,Nom complet,Naixament_Espanya
DNI,,,,,,,,,,,,,
16928694K,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Dona,1.144 €,No,Grup B,Inês Ferreira Silva,No
27724652S,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Dona,1.253 €,Sí,Grup A,Clara Sánchez Martínez,Sí
38141675A,Fatima,Fassi,Marroc,Rabat,6,11,2005,Altres,1.441 €,Sí,Grup A,Fatima Fassi,No
59157262R,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Dona,1.944 €,No,Grup B,Khadija Bennani Bennani,No
69630528M,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Home,1.043 €,No,Grup A,Toni Sánchez García,Sí
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Dona,1.216 €,No,Grup B,Marta Ferrer Ferrer,Sí
52145541P,Joan,García,Espanya,Sevilla,11,4,1959,Home,971 €,No,Grup A,Joan García,Sí
69760120X,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Dona,682 €,No,Grup A,Laia Ferrer Martínez,Sí
82947791W,Jordi,García,Espanya,Barcelona,23,5,1984,Home,1.699 €,Sí,Grup C,Jordi García,Sí
89253307W,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Dona,1.217 €,No,Grup A,Clara Sánchez López,Sí

#### 4.
Crea una taula resum que permeti veure el sou mig, medià, mínim i màxim per Gènere.

Ordena la taula en funció del sou mig.

In [128]:

df_cap['Salari mensual'] = df_cap['Salari mensual'].astype(str)

df_cap['Salari mensual'] = (df_cap['Salari mensual'].str.replace('€', '', regex=False).str.replace('.', '', regex=False).str.strip())

df_cap['Salari mensual'] = pd.to_numeric(df_cap['Salari mensual'], errors='coerce')


df_sous = df_cap.groupby('Gènere')['Salari mensual'].agg(['mean','median','min','max']).reset_index()

df_sous= df_sous.sort_values('mean')
df_sous=df_sous.round(2)
df_sous

   Gènere     mean  median  min   max
2    Home  2385.92  1632.0   10  9970
0  Altres  2601.59  1574.0  124  9960
1    Dona  2792.12  1521.5   11  9990

#### 5.
Crea una taula resum amb el salari mig per gènere (files) i país d'origen (columnes).

Afegeix-hi les mitjanes als marges de la taula.

(EXTRA): Aplica format condicional a la taula per veure en un color més intens els valors més elevats

In [ ]:
# formula poc exacte perquè fa les mitjanes de les mitjanes.. no les mitjanes reals totals (als marges)
d_sous_pais= df_cap.pivot_table(index='Gènere', columns = "País d'origen", values = 'Salari mensual', aggfunc = 'mean', margins=True, margins_name='Total', fill_value=0)

d_sous_pais=d_sous_pais.round(2)

d_sous_pais.style.background_gradient(cmap='YlOrRd', axis=1)

#### 6.
Crea una columna nova que sigui la data de naixament en format Datetime a partir de les columnes dia, mes i any. Utilitzant aquesta columna crea una funció que donada una data, et calculi l'edat actual a dia d'avui.

Utilitza la funció que acabes de crear per generar una columna nova al DataFrame amb l'edat actual.

In [149]:
df_cap['Data_Naixement'] = pd.to_datetime(df_cap[['Any', 'Mes', 'Dia']].rename(columns={
    'Any': 'year',
    'Mes': 'month',
    'Dia': 'day'
}))

def calcul_edat(naixement):
    if pd.isnull(naixement):
        return None
    avui = date.today()
    edat = avui.year - naixement.year - ((avui.month, avui.day)< (naixement.month, naixement.day))
    return edat

df_cap ['Edat'] = df_cap['Data_Naixement'].apply(calcul_edat)

display(df_cap)

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,Grup Professional,Nom complet,Naixament_Espanya,Data_Naixement,Edat
DNI,,,,,,,,,,,,,,,
16928694K,Inês,Ferreira Silva,Portugal,Lisboa,25,2,1953,Dona,1144,No,Grup B,Inês Ferreira Silva,No,1953-02-25,73
27724652S,Clara,Sánchez Martínez,Espanya,Barcelona,18,3,1996,Dona,1253,Sí,Grup A,Clara Sánchez Martínez,Sí,1996-03-18,30
38141675A,Fatima,Fassi,Marroc,Rabat,6,11,2005,Altres,1441,Sí,Grup A,Fatima Fassi,No,2005-11-06,20
59157262R,Khadija,Bennani Bennani,Marroc,Rabat,20,1,1995,Dona,1944,No,Grup B,Khadija Bennani Bennani,No,1995-01-20,31
69630528M,Toni,Sánchez García,Espanya,Barcelona,9,8,1999,Home,1043,No,Grup A,Toni Sánchez García,Sí,1999-08-09,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25161375F,Marta,Ferrer Ferrer,Espanya,Sevilla,1,6,1951,Dona,1216,No,Grup B,Marta Ferrer Ferrer,Sí,1951-06-01,74
52145541P,Joan,García,Espanya,Sevilla,11,4,1959,Home,9710,No,Grup A,Joan García,Sí,1959-04-11,67
69760120X,Laia,Ferrer Martínez,Espanya,Barcelona,11,11,1980,Dona,6820,No,Grup A,Laia Ferrer Martínez,Sí,1980-11-11,45
82947791W,Jordi,García,Espanya,Barcelona,23,5,1984,Home,1699,Sí,Grup C,Jordi García,Sí,1984-05-23,41
89253307W,Clara,Sánchez López,Espanya,Bilbao,1,8,1952,Dona,1217,No,Grup A,Clara Sánchez López,Sí,1952-08-01,73